export const products = [
  {
    id: "p001",
    title: "Classic Cotton T-Shirt",
    image:"/1.jpg",
    bestSeller: true,
    specialProduct: true,
    featuredProduct: false,
    category: "men",
    productCategory: "topwear",
    subcategory: "t-shirt",
    date: "2025-05-10",
    description: "Classic cotton t-shirt with round neck.",
    price: 19.99,
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: "p002",
    title: "High-Waisted Skinny Jeans",
    bestSeller: false,
    specialProduct: false,
    featuredProduct: true,
    category: "women",
    productCategory: "bottomwear",
    subcategory: "jeans",
    date: "2025-04-25",
    description: "High-waisted skinny jeans with stretchable fabric.",
    price: 39.99,
    sizes: ["S", "M", "L"],
  },
  {
    id: "p003",
    title: "Kids Fleece Hoodie",
    bestSeller: true,
    specialProduct: false,
    featuredProduct: true,
    category: "children",
    productCategory: "outerwear",
    subcategory: "hoodie",
    date: "2025-03-12",
    description: "Warm fleece hoodie for kids with front pockets.",
    price: 24.99,
    sizes: ["XS", "S", "M"],
  },
  {
    id: "p004",
    title: "Men's Bomber Jacket",
    bestSeller: false,
    specialProduct: true,
    featuredProduct: false,
    category: "men",
    productCategory: "outerwear",
    subcategory: "jacket",
    date: "2025-01-30",
    description: "Water-resistant bomber jacket with zip closure.",
    price: 59.99,
    sizes: ["M", "L", "XL", "XXL"],
  },
  {
    id: "p005",
    title: "Floral Summer Dress",
    bestSeller: true,
    specialProduct: true,
    featuredProduct: true,
    category: "women",
    productCategory: "onepiece",
    subcategory: "dress",
    date: "2025-05-01",
    description: "Floral summer dress with adjustable straps.",
    price: 49.99,
    sizes: ["S", "M", "L"],
  },
  {
    id: "p006",
    title: "Kids Cotton Shorts",
    bestSeller: false,
    specialProduct: false,
    featuredProduct: false,
    category: "children",
    productCategory: "bottomwear",
    subcategory: "shorts",
    date: "2025-04-15",
    description: "Cotton shorts with elastic waistband for kids.",
    price: 14.99,
    sizes: ["XS", "S", "M"],
  },
  {
    id: "p007",
    title: "Slim-Fit Formal Shirt",
    bestSeller: true,
    specialProduct: true,
    featuredProduct: true,
    category: "men",
    productCategory: "topwear",
    subcategory: "shirt",
    date: "2025-02-18",
    description: "Slim-fit formal shirt made from breathable fabric.",
    price: 29.99,
    sizes: ["M", "L", "XL"],
  },
  {
    id: "p008",
    title: "Pleated Midi Skirt",
    bestSeller: false,
    specialProduct: false,
    featuredProduct: false,
    category: "women",
    productCategory: "bottomwear",
    subcategory: "skirt",
    date: "2025-03-05",
    description: "Pleated midi skirt with a comfortable waistband.",
    price: 34.99,
    sizes: ["S", "M", "L"],
  },
  {
    id: "p009",
    title: "Cartoon Pajama Set",
    bestSeller: true,
    specialProduct: false,
    featuredProduct: true,
    category: "children",
    productCategory: "sleepwear",
    subcategory: "pajamas",
    date: "2025-01-15",
    description: "Soft cotton pajamas set with fun cartoon prints.",
    price: 19.99,
    sizes: ["XS", "S", "M"],
  },
  {
    id: "p010",
    title: "Men's Office Trousers",
    bestSeller: false,
    specialProduct: true,
    featuredProduct: false,
    category: "men",
    productCategory: "bottomwear",
    subcategory: "trousers",
    date: "2025-02-01",
    description: "Comfort-fit trousers perfect for office wear.",
    price: 44.99,
    sizes: ["M", "L", "XL", "XXL"],
  },
  {
    id: "p011",
    title: "Chiffon Embroidered Blouse",
    bestSeller: true,
    specialProduct: true,
    featuredProduct: true,
    category: "women",
    productCategory: "topwear",
    subcategory: "blouse",
    date: "2025-04-10",
    description: "Chiffon blouse with floral embroidery details.",
    price: 27.99,
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: "p012",
    title: "Children's Graphic T-Shirt",
    bestSeller: false,
    specialProduct: false,
    featuredProduct: false,
    category: "children",
    productCategory: "topwear",
    subcategory: "t-shirt",
    date: "2025-03-28",
    description: "Brightly colored graphic t-shirt for children.",
    price: 12.99,
    sizes: ["XS", "S", "M"],
  },
  {
    id: "p013",
    title: "Wool Crew Neck Sweater",
    bestSeller: true,
    specialProduct: true,
    featuredProduct: false,
    category: "men",
    productCategory: "topwear",
    subcategory: "sweater",
    date: "2025-01-22",
    description: "Wool sweater with crew neck and ribbed cuffs.",
    price: 49.99,
    sizes: ["M", "L", "XL"],
  },
  {
    id: "p014",
    title: "Stretch Workout Leggings",
    bestSeller: false,
    specialProduct: false,
    featuredProduct: true,
    category: "women",
    productCategory: "bottomwear",
    subcategory: "leggings",
    date: "2025-03-03",
    description: "Stretchable leggings perfect for workouts and yoga.",
    price: 22.99,
    sizes: ["S", "M", "L"],
  },
  {
    id: "p015",
    title: "Children's Windbreaker Jacket",
    bestSeller: true,
    specialProduct: true,
    featuredProduct: true,
    category: "children",
    productCategory: "outerwear",
    subcategory: "jacket",
    date: "2025-04-20",
    description: "Lightweight windbreaker jacket for children.",
    price: 29.99,
    sizes: ["S", "M", "L"],
  }
];
